export const typography = {
  /// styleguid
  'text-sm/Light': 'text-sm font-light',
  'text-sm/Regular': 'text-sm font-normal',
  'text-sm/Medium': 'text-sm font-medium',
  'text-sm/Semibold': 'text-sm font-semibold',
  'text-sm/Bold': 'text-sm font-bold',

  'text-base/Light': 'text-base font-light',
  'text-base/Regular': 'text-base font-normal',
  'text-base/Medium': 'text-base font-medium',
  'text-base/Semibold': 'text-base font-semibold',
  'text-base/Bold': 'text-base font-bold',

  'text-md/Light': 'text-md font-light',
  'text-md/Regular': 'text-md font-normal',
  'text-md/Medium': 'text-md font-medium',
  'text-md/Semibold': 'text-md font-semibold',
  'text-md/Bold': 'text-md font-bold',

  'text-lg/Light': 'text-lg font-light',
  'text-lg/Regular': 'text-lg font-normal',
  'text-lg/Medium': 'text-lg font-medium',
  'text-lg/Semibold': 'text-lg font-semibold',
  'text-lg/Bold': 'text-lg font-bold',

  'text-xl/Light': 'text-xl font-light',
  'text-xl/Regular': 'text-xl font-normal',
  'text-xl/Medium': 'text-xl font-medium',
  'text-xl/Semibold': 'text-xl font-semibold',
  'text-xl/Bold': 'text-xl font-bold',

  'text-2xl/Light': 'text-2xl font-light',
  'text-2xl/Regular': 'text-2xl font-normal',
  'text-2xl/Medium': 'text-2xl font-medium',
  'text-2xl/Semibold': 'text-2xl font-semibold',
  'text-2xl/Bold': 'text-2xl font-bold',

  'text-4xl/Light': 'text-4xl font-light',
  'text-4xl/Regular': 'text-4xl font-normal',
  'text-4xl/Medium': 'text-4xl font-medium',
  'text-4xl/Semibold': 'text-4xl font-semibold',
  'text-4xl/Bold': 'text-4xl font-bold',

  'text-title/Light': 'text-title font-sans font-light',
  'text-title/Regular': 'text-title font-sans font-normal',
  'text-title/Medium': 'text-title font-sans font-medium',
  'text-title/Semibold': 'text-title font-sans font-semibold',
  'text-title/Bold': 'text-title font-sans font-bold',

  'text-huge-headline/Light': 'text-huge-headline font-sans font-light',
  'text-huge-headline/Regular': 'text-huge-headline font-sans font-normal',
  'text-huge-headline/Medium': 'text-huge-headline font-sans font-medium',
  'text-huge-headline/Semibold': 'text-huge-headline font-sans font-semibold',
  'text-huge-headline/Bold': 'text-huge-headline font-sans font-bold',

  'text-big-title/Light': 'text-big-title font-sans font-light',
  'text-big-title/Regular': 'text-big-title font-sans font-normal',
  'text-big-title/Medium': 'text-big-title font-sans font-medium',
  'text-big-title/Semibold': 'text-big-title font-sans font-semibold',
  'text-big-title/Bold': 'text-big-title font-sans font-bold',

  'text-body/Light': 'text-body font-mono font-light',
  'text-body/Regular': 'text-body font-mono font-normal',
  'text-body/Medium': 'text-body font-mono font-medium',
  'text-body/Semibold': 'text-body font-mono font-semibold',
  'text-body/Bold': 'text-body font-mono font-bold',

  'text-quote/Light': 'text-quote font-quote font-light',
  'text-quote/Regular': 'text-quote font-quote font-normal',
  'text-quote/Medium': 'text-quote font-quote font-medium',
  'text-quote/Semibold': 'text-quote font-quote font-semibold',
  'text-quote/Bold': 'text-quote font-quote font-bold',

  'text-caption/Light': 'text-caption font-mono font-light',
  'text-caption/Regular': 'text-caption font-mono font-normal',
  'text-caption/Medium': 'text-caption font-mono font-medium',
  'text-caption/Semibold': 'text-caption font-mono font-semibold',
  'text-caption/Bold': 'text-caption font-mono font-bold',
};
