import type { Meta, StoryObj } from '@storybook/react';
import React from 'react';

import { Constats } from './Constats';
import imgCheckBoxLInes from './statics/constats-situation.png';

const meta: Meta<typeof Constats> = {
  title: 'Form elements/Constats',
  component: Constats,
};

const items = [
  {
    checkedB: false,
    valueB: 'x',
    name: 'constats1',
    number: '1',
    title:
      "Heurtait à l'arrière, en roulant dans le meme sens et sur une meme file",
    checkedA: false,
    valueA: '1',
    hrExist: false,
  },
  {
    checkedB: false,
    valueB: 'x',
    name: 'constats2',
    number: '2',
    title: 'Roulait dans le même sens et sur une file différente',
    checkedA: false,
    valueA: '2',
    hrExist: false,
  },
  {
    checkedB: false,
    valueB: 'x',
    name: 'constats3',
    number: '3',
    title: 'Roulait en sens inverse',
    checkedA: false,
    valueA: '3',
    hrExist: false,
  },
  {
    checkedB: false,
    valueB: 'x',
    name: 'constats4',
    number: '4',
    title: "Provenait d'une chaussée différente",
    checkedA: false,
    valueA: '4',
    hrExist: false,
  },
  {
    checkedB: false,
    valueB: 'x',
    name: 'constats5',
    number: '5',
    title: 'Venait de droite ( dans un carrefour)',
    checkedA: false,
    valueA: '5',
    hrExist: true,
  },
  {
    checkedB: false,
    valueB: 'x',
    name: 'constats6',
    number: '6',
    title: 'S’engageait sur une place à sens giratoire',
    checkedA: false,
    valueA: '6',
    hrExist: false,
  },
  {
    checkedB: false,
    valueB: 'x',
    name: 'constats7_1',
    number: '7',
    title: 'Roulait sur une place à sens giratoire',
    checkedA: false,
    valueA: '7',
    hrExist: true,
  },
  {
    checkedB: false,
    valueB: 'x',
    name: 'constats7',
    number: '7',
    title: 'Roulait sur une place à sens giratoire',
    checkedA: false,
    valueA: '7',
    hrExist: false,
  },
  {
    checkedB: false,
    valueB: 'x',
    name: 'constats8',
    number: '8',
    title: 'En stationnement',
    checkedA: false,
    valueA: '8',
    hrExist: false,
  },
  {
    checkedB: false,
    valueB: 'x',
    name: 'constats9',
    number: '9',
    title: 'Quittait un stationnement',
    checkedA: false,
    valueA: '9',
    hrExist: false,
  },
  {
    checkedB: false,
    valueB: 'x',
    name: 'constats10',
    number: '10',
    title: 'Prenait un stationnement',
    checkedA: false,
    valueA: '10',
    hrExist: true,
  },
  {
    checkedB: false,
    valueB: 'x',
    name: 'constats11',
    number: '11',
    title: 'Reculait',
    checkedA: false,
    valueA: '11',
    hrExist: false,
  },
  {
    checkedB: false,
    valueB: 'x',
    name: 'constats12',
    number: '12',
    title: 'Doublait (dépassait)',
    checkedA: false,
    valueA: '12',
    hrExist: false,
  },
  {
    checkedB: false,
    valueB: 'x',
    name: 'constats13',
    number: '13',
    title: 'Dépassement irrégulier',
    checkedA: false,
    valueA: '13',
    hrExist: false,
  },
  {
    checkedB: false,
    valueB: 'x',
    name: 'constats14',
    number: '14',
    title: 'Changeait de file',
    checkedA: false,
    valueA: '14',
    hrExist: false,
  },
  //
  {
    checkedB: false,
    valueB: 'x',
    name: 'constats15',
    number: '15',
    title: 'Virait à droite',
    checkedA: false,
    valueA: '15',
    hrExist: false,
  },
  {
    checkedB: false,
    valueB: 'x',
    name: 'constats16',
    number: '16',
    title: 'Virait à gauche',
    checkedA: false,
    valueA: '16',
    hrExist: true,
  },
  {
    checkedB: false,
    valueB: 'x',
    name: 'constats17',
    number: '17',
    title: 'S’engageait dans un parking, un lieu privé, un chemin de terre',
    checkedA: false,
    valueA: '17',
    hrExist: false,
  },
  {
    checkedB: false,
    valueB: 'x',
    name: 'constats18',
    number: '18',
    title: 'Sortait d’un parking, d’un lieu privé, d’un chemin de terre',
    checkedA: false,
    valueA: '18',
    hrExist: true,
  },
  {
    checkedB: false,
    valueB: 'x',
    name: 'constats19',
    number: '19',
    title:
      'Empiétait sur la partie de chaussée réservée à la circulation en sens inverse',
    checkedA: false,
    valueA: '19',
    hrExist: false,
  },
  {
    checkedB: false,
    valueB: 'x',
    name: 'constats20',
    number: '20',
    title: 'Roulait en sens interdit',
    checkedA: false,
    valueA: '20',
    hrExist: false,
  },
  {
    checkedB: false,
    valueB: 'x',
    name: 'constats21',
    number: '21',
    title: 'N’a pas respecté un signal de priorité',
    checkedA: false,
    valueA: '21',
    hrExist: false,
  },
  {
    checkedB: false,
    valueB: 'x',
    name: 'constats2é',
    number: '22',
    title: 'Faisait un demi tour',
    checkedA: false,
    valueA: '22',
    hrExist: false,
  },
  {
    checkedB: false,
    valueB: 'x',
    name: 'constats23',
    number: '23',
    title: 'Ouvrait une portiére',
    checkedA: false,
    valueA: '23',
    hrExist: false,
  },
];

export default meta;
type Story = StoryObj<typeof Constats>;

export const Primary: Story = {
  args: {
    //title: 'test',
    items: items,
    constatImg: {
      src: imgCheckBoxLInes,
      width: 300,
      height: 150,
    },
  },
  render: (args) => (
    <div>
      <Constats {...args} />
    </div>
  ),
};
